'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Paintball.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftCrouch1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftCrouch1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftCrouch2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftCrouch2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftCrouch3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftCrouch3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftCrouch4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftCrouch4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftCrouch5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftCrouch5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftCrouch6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftCrouch6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftCrouch7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftCrouch7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftCrouch8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftCrouch8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftIdle9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftIdle9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueLeftRun9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueLeftRun9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightCrouch1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightCrouch1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightCrouch2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightCrouch2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightCrouch3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightCrouch3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightCrouch4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightCrouch4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightCrouch5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightCrouch5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightCrouch6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightCrouch6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightCrouch7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightCrouch7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightCrouch8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightCrouch8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightIdle9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightIdle9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueRightRun9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueRightRun9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueTrophy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueTrophy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bothTrophy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bothTrophy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnGameTime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnGameTime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnMainMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMainMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnMusic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnMusic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnOptionsAudioTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOptionsAudioTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnOptionsGameTab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOptionsGameTab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnPowerUps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnPowerUps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnSfx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSfx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frmBkgd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmBkgd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gameTimeFiveMinutesText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gameTimeFiveMinutesText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gameTimeOneHalfMinutesText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gameTimeOneHalfMinutesText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gameTimeTenMinutesText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gameTimeTenMinutesText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gameTimeTwoHalfMinutesText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gameTimeTwoHalfMinutesText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gameTimeUnlimitedText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gameTimeUnlimitedText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property htpJump() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("htpJump", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property htpMove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("htpMove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property htpRun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("htpRun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property htpShoot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("htpShoot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property htpTime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("htpTime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InvisibleSideWall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvisibleSideWall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property invisibleTopWall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invisibleTopWall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loadingBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadingBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loadingRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadingRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mainFloor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainFloor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newPBLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newPBLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeLeftCursorIdle9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeLeftCursorIdle9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orangeRightCursorIdle9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orangeRightCursorIdle9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property paintballLogo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("paintballLogo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pf9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pf9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picBlueWins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picBlueWins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picBothWin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picBothWin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picGetReady() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picGetReady", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picNo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picNo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picPlayAgain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picPlayAgain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picRedWins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picRedWins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picYes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picYes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powerup_ammo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerup_ammo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powerup_health() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerup_health", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powerup_shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerup_shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powerup_slowdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerup_slowdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powerup_speedup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerup_speedup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powerup_triple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerup_triple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pupsDisabledText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pupsDisabledText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pupsEnabledText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pupsEnabledText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftCrouch1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftCrouch1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftCrouch2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftCrouch2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftCrouch3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftCrouch3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftCrouch4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftCrouch4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftCrouch5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftCrouch5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftCrouch6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftCrouch6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftCrouch7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftCrouch7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftCrouch8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftCrouch8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftIdle9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftIdle9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redLeftRun9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLeftRun9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightCrouch1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightCrouch1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightCrouch2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightCrouch2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightCrouch3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightCrouch3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightCrouch4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightCrouch4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightCrouch5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightCrouch5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightCrouch6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightCrouch6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightCrouch7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightCrouch7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightCrouch8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightCrouch8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightIdle9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightIdle9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redRightRun9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redRightRun9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redTrophy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redTrophy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shotBlueWide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shotBlueWide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shotOrangeWide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shotOrangeWide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shotRedWide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shotRedWide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sound25Text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sound25Text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sound50Text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sound50Text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sound75Text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sound75Text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property soundMaxText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soundMaxText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property soundMutedText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soundMutedText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tempButtonArcade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tempButtonArcade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tempButtonHTP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tempButtonHTP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tempButtonOptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tempButtonOptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tempButtonPlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tempButtonPlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
